# Generated by Django 5.2.4 on 2025-07-04 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachAppointment',
            new_name='Appointment',
        ),
    ]
