# Generated by Django 5.2.4 on 2025-07-07 05:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0002_rename_coachappointment_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('time__gte', datetime.time(8, 0)), ('time__lte', datetime.time(19, 0))), name='appointment_time_between_8_and_19'),
        ),
    ]
