# Generated by Django 5.2.4 on 2025-07-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0003_appointment_appointment_time_between_8_and_19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True, verbose_name='Appointment time'),
        ),
    ]
