# Generated by Django 5.2.4 on 2025-07-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0006_remove_appointment_appointment_date_in_future_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
    ]
