# Generated by Django 5.2.4 on 2025-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0007_remove_appointment_note'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_date_in_future',
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
