# Generated by Django 5.2.4 on 2025-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0008_remove_appointment_appointment_date_in_future_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
