# Generated by Django 5.2.4 on 2025-07-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0009_appointment_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_subject',
            new_name='subject',
        ),
    ]
