# Generated by Django 5.2.4 on 2025-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0010_rename_appointment_subject_appointment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='subject',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_subject',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
