# Generated by Django 5.2.4 on 2025-07-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0011_remove_appointment_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_subject',
            new_name='subject',
        ),
    ]
