# Generated by Django 5.2.4 on 2025-07-08 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0012_rename_appointment_subject_appointment_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
