# Generated by Django 5.2.4 on 2025-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_appointment_site', '0016_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
